name: lanterner
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.22.0
  email_validator: ^2.0.1
  smart_select: ^4.3.2
  # smooth_page_indicator: ^0.2.3
  material_design_icons_flutter: ^4.0.5955
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.2
  cloud_firestore: ^1.0.7
  firebase_storage: ^8.0.5
  firebase_performance: ^0.7.0+3
    
  persistent_bottom_nav_bar: ^4.0.2
  cached_network_image: ^3.0.0
  image_picker: ^0.7.4
  auto_direction: ^0.0.5
  photo_view: ^0.11.1
  timeago: ^3.0.2
  modal_bottom_sheet: ^2.0.0
  filter_list: ^1.0.0
  logger: ^1.0.0
  translator: ^0.1.7
  shared_preferences: ^2.0.6
  tap_debouncer: ^2.0.0
  fluttertoast: ^8.0.7
  audioplayers: ^0.19.1
  flutter_audio_recorder2: ^0.0.2
  path_provider: ^2.0.2
  timer_builder: ^2.0.0
  animations: ^2.0.1
dev_dependencies:
  flutter_launcher_icons:

  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/icon.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/
    - assets/images/
    # - assets/images/wishes.svg
    # - assets/images/user1.jpeg
    # - assets/images/avatar_bg.jpg

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # TODO: check if openSans is actually working
  fonts:
    - family: Forte
      fonts:
        - asset: assets/fonts/FORTE.TTF
        - asset: assets/fonts/OpenSans-Regular.ttf
